name: RonlabGameAssistant
version: '1.0.0'
main: com.ronlab.rga.RGA
api-version: '1.21'
description: All-in-one game assistant for the Ronlab server.
authors: [ ]

commands:
  rga:
    description: Ronlab Game Assistant admin command.
    usage: /rga <reload|tp|conclude|createworld|compass>
    permission: rga.admin
  hub:
    description: Return to the Hub world.
    usage: /hub
    permission: rga.hub

permissions:
  rga.admin:
    description: Access to all RGA admin commands.
    default: op
  rga.hub:
    description: Allows use of the /hub command.
    default: true
    
